NAClicker:
  minCps: 8
  values:
  - 9
  - 11
  - 11
  - 11
  - 12
  - 10
  - 11
  - 9
  - 10
  - 13
  - 15
MantheClicker:
  minCps: 7
  values:
  - 14
  - 13
  - 14
  - 13
  - 13
  - 10
  - 11
  - 11
  - 11
  - 12
